name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Publish to Github Packages
        uses: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Publish to Docker Hub
      uses: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: annietrusty/homework
        tags: vX.Y.Z
